// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgWPok-R3nxMJTlvovKXXHmuTiOELMWEs',
    appId: '1:536345184770:web:78b8006a493eb92151b51b',
    messagingSenderId: '536345184770',
    projectId: 'catcrud-95002',
    authDomain: 'catcrud-95002.firebaseapp.com',
    storageBucket: 'catcrud-95002.firebasestorage.app',
    measurementId: 'G-JXHN0BWPXP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiQPLFB9_WDXky6v4tydlUE0AqSoZxP2E',
    appId: '1:536345184770:android:80e46649e46bdc7051b51b',
    messagingSenderId: '536345184770',
    projectId: 'catcrud-95002',
    storageBucket: 'catcrud-95002.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6LrZEfEm22bClIq1QGn6X0zyMuCtm-tU',
    appId: '1:536345184770:ios:24bfbcb11eef902751b51b',
    messagingSenderId: '536345184770',
    projectId: 'catcrud-95002',
    storageBucket: 'catcrud-95002.firebasestorage.app',
    iosBundleId: 'com.example.flutternews',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6LrZEfEm22bClIq1QGn6X0zyMuCtm-tU',
    appId: '1:536345184770:ios:24bfbcb11eef902751b51b',
    messagingSenderId: '536345184770',
    projectId: 'catcrud-95002',
    storageBucket: 'catcrud-95002.firebasestorage.app',
    iosBundleId: 'com.example.flutternews',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgWPok-R3nxMJTlvovKXXHmuTiOELMWEs',
    appId: '1:536345184770:web:08400793d5e888a651b51b',
    messagingSenderId: '536345184770',
    projectId: 'catcrud-95002',
    authDomain: 'catcrud-95002.firebaseapp.com',
    storageBucket: 'catcrud-95002.firebasestorage.app',
    measurementId: 'G-MRHJC33NQF',
  );

}